"""Build the macOS launcher app: ``~/Applications/Claude Explorer.app``.

Why: many users never open a terminal. The launcher lets them start Claude
Explorer from the Dock, Launchpad, or Spotlight, like any other app.

What it is: an AppleScript "stay-open" applet, compiled with ``osacompile``
on the user's own Mac. A file made locally carries no quarantine flag, so
macOS opens it without Gatekeeper, a paid Developer ID, or notarization.

What it does:

* Open the app. If nothing answers on the port, it starts
  ``claude-explorer serve`` in the background and waits for it. Then it
  opens the browser.
* Click the Dock icon again. It opens the browser again, and restarts the
  server if the server stopped.
* Quit the app. It stops the server, but only a server that it started. A
  server that the user started in a terminal keeps running.

Server output goes to ``~/Library/Logs/claude-explorer-serve.log``.

The applet runs the ``claude-explorer`` entry point that sits next to
``sys.executable``. After ``uv tool install`` that path stays the same
across ``uv tool upgrade``, so the app keeps working after an upgrade.
"""

from __future__ import annotations

import plistlib
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import click

APP_NAME = "Claude Explorer.app"
BUNDLE_ID = "com.claude-explorer.launcher"
DEFAULT_PORT = 8765
_ICON_PNG = Path(__file__).resolve().parent / "assets" / "app-icon.png"


def default_dest() -> Path:
    """``~/Applications``: needs no admin rights, and Spotlight indexes it."""
    return Path.home() / "Applications"


def default_log_path() -> Path:
    return Path.home() / "Library" / "Logs" / "claude-explorer-serve.log"


def _as_literal(value: str) -> str:
    """Return ``value`` as an AppleScript string literal."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def build_applescript(*, executable: str, port: int, log_path: str) -> str:
    """Return the applet source with the executable, port and log baked in.

    The script keeps its state in globals. An applet saves changed
    *properties* back into its own bundle, which would break the bundle's
    signature.
    """
    exe = _as_literal(executable)
    log = _as_literal(log_path)
    url = _as_literal(f"http://localhost:{port}")
    probe = _as_literal(
        f"curl -fsS -o /dev/null --max-time 1 http://127.0.0.1:{port}/api/config"
    )
    return f"""-- Generated by `claude-explorer install-app`. Run that command again to
-- regenerate this app; do not edit it by hand.
global serverPID
global ownsServer

on run
	set serverPID to ""
	set ownsServer to false
	my ensureServer()
end run

on reopen
	my ensureServer()
end reopen

on ensureServer()
	if not my serverUp() then
		if not my startServer() then return
	end if
	open location {url}
end ensureServer

on startServer()
	set exe to {exe}
	set logFile to {log}
	try
		do shell script "test -x " & quoted form of exe
	on error
		display dialog "Claude Explorer is not installed at:" & return & exe & return & return & "Install it again, then run: claude-explorer install-app" buttons {{"OK"}} default button "OK" with icon stop
		quit
		return false
	end try
	-- Redirect stdin, stdout and stderr, and background ONLY the server.
	-- Anything that keeps this command's output pipe open blocks the app,
	-- and a blocked app cannot receive Quit.
	set serverPID to do shell script "nohup " & quoted form of exe & " serve --port {port} >> " & quoted form of logFile & " 2>&1 < /dev/null & echo $!"
	set ownsServer to true
	repeat 120 times
		if my serverUp() then return true
		try
			do shell script "kill -0 " & serverPID
		on error
			exit repeat
		end try
		delay 0.5
	end repeat
	set ownsServer to false
	display dialog "Claude Explorer did not start." & return & return & "The log is at:" & return & logFile buttons {{"Open Log", "OK"}} default button "OK" with icon caution
	if button returned of result is "Open Log" then do shell script "open -a Console " & quoted form of logFile
	quit
	return false
end startServer

on serverUp()
	try
		do shell script {probe}
		return true
	on error
		return false
	end try
end serverUp

on quit
	if ownsServer and serverPID is not "" then
		try
			do shell script "kill " & serverPID
		end try
	end if
	continue quit
end quit
"""


def _require_ours(app: Path) -> None:
    info = app / "Contents" / "Info.plist"
    try:
        bundle_id = plistlib.loads(info.read_bytes()).get("CFBundleIdentifier")
    except (OSError, plistlib.InvalidFileException):
        bundle_id = None
    if bundle_id != BUNDLE_ID:
        raise click.ClickException(
            f"{app} exists but is not the Claude Explorer launcher "
            f"(bundle id {bundle_id!r}). Move it away, then try again."
        )


def _make_icns(workdir: Path) -> Path:
    """Build an .icns from the packaged PNG with the macOS tools sips and iconutil."""
    iconset = workdir / "app.iconset"
    iconset.mkdir()
    for size in (16, 32, 128, 256, 512):
        for scale, suffix in ((1, ""), (2, "@2x")):
            px = size * scale
            subprocess.run(
                ["sips", "-z", str(px), str(px), str(_ICON_PNG),
                 "--out", str(iconset / f"icon_{size}x{size}{suffix}.png")],
                check=True, capture_output=True,
            )
    icns = workdir / "app.icns"
    subprocess.run(
        ["iconutil", "-c", "icns", str(iconset), "-o", str(icns)],
        check=True, capture_output=True,
    )
    return icns


def build_app(*, dest: Path, executable: str, port: int, log_path: Path) -> Path:
    """Compile, brand, sign and install the launcher. Return its path."""
    dest.mkdir(parents=True, exist_ok=True)
    target = dest / APP_NAME
    if target.exists():
        _require_ours(target)

    with tempfile.TemporaryDirectory() as tmp:
        work = Path(tmp)
        source = work / "launcher.applescript"
        source.write_text(
            build_applescript(executable=executable, port=port, log_path=str(log_path)),
            encoding="utf-8",
        )
        built = work / APP_NAME
        subprocess.run(
            ["osacompile", "-s", "-o", str(built), str(source)],
            check=True, capture_output=True,
        )

        info_path = built / "Contents" / "Info.plist"
        info = plistlib.loads(info_path.read_bytes())
        info["CFBundleIdentifier"] = BUNDLE_ID
        info["CFBundleName"] = "Claude Explorer"
        info_path.write_bytes(plistlib.dumps(info))

        if _ICON_PNG.is_file():
            shutil.copyfile(_make_icns(work), built / "Contents" / "Resources" / "applet.icns")

        # The Info.plist and icon edits break the ad-hoc signature that
        # osacompile applied, so sign the finished bundle again.
        subprocess.run(
            ["codesign", "--force", "-s", "-", str(built)],
            check=True, capture_output=True,
        )

        if target.exists():
            shutil.rmtree(target)
        shutil.move(str(built), str(target))
    return target


def uninstall_app(dest: Path) -> bool:
    """Remove the launcher from ``dest``. Return False if it was not there."""
    target = dest / APP_NAME
    if not target.exists():
        return False
    _require_ours(target)
    shutil.rmtree(target)
    return True


def launcher_executable() -> str:
    """The ``claude-explorer`` entry point of the running environment."""
    return str(Path(sys.executable).with_name("claude-explorer"))
